# Generated by Django 4.2.14 on 2024-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_profile_saved_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
